using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Selenium2016.Models
{
    public class Countries
    {
        public List<string> Name;

        public Countries()
        {
            Name = new List<string>();
            Name.Add("FRANCE");
            Name.Add("GERMANY");
            Name.Add("ITALY");
            Name.Add("SPAIN");
            Name.Add("UNITED KINGDOM");
            Name.Add("ABU DHABI");
            Name.Add("ADEN");
            Name.Add("AFGHANISTAN");
            Name.Add("ALBANIA");
            Name.Add("ALGERIA");
            Name.Add("AMERICAN SAMOA");
            Name.Add("ANDORRA");
            Name.Add("ANGOLA");
            Name.Add("ANTARCTICA");
            Name.Add("ANTIGUA");
            Name.Add("ARGENTINA");
            Name.Add("ARMENIA");
            Name.Add("ARUBA");
            Name.Add("AUSTRALIA");
            Name.Add("AUSTRIA");
            Name.Add("AZERBAIJAN");
            Name.Add("BAHAMAS");
            Name.Add("BAHRAIN");
            Name.Add("BANGLADESH");
            Name.Add("BARBADOS");
            Name.Add("BELARUS");
            Name.Add("BELGIUM");
            Name.Add("BELIZE");
            Name.Add("BENIN");
            Name.Add("BERMUDA");
            Name.Add("BHUTAN");
            Name.Add("BOLIVIA");
            Name.Add("BOSNIA");
            Name.Add("BOTSWANA");
            Name.Add("BOUVET ISLAND");
            Name.Add("BRAZIL");
            Name.Add("BRITISH ANTARCTICA TERRITORY");
            Name.Add("BRITISH INDIAN OCEAN TERRITORY");
            Name.Add("BRITISH VIRGIN ISLANDS");
            Name.Add("BRITISH WEST INDIES");
            Name.Add("BRUNEI");
            Name.Add("BULGARIA");
            Name.Add("BURKINA FASO");
            Name.Add("BURUNDI");
            Name.Add("CAMBODIA");
            Name.Add("CAMEROON");
            Name.Add("CANADA");
            Name.Add("CANAL ZONE");
            Name.Add("CANARY ISLAND");
            Name.Add("CAPE VERDI ISLANDS");
            Name.Add("CAYMAN ISLANDS");
            Name.Add("CEVLON");
            Name.Add("CHAD");
            Name.Add("CHANNEL ISLAND UK");
            Name.Add("CHILE");
            Name.Add("CHINA");
            Name.Add("CHRISTMAS ISLAND");
            Name.Add("COCOS (KEELING) ISLAND");
            Name.Add("COLOMBIA");
            Name.Add("COMORO ISLANDS");
            Name.Add("CONGO");
            Name.Add("CONGO KINSHASA");
            Name.Add("COOK ISLANDS");
            Name.Add("COSTA RICA");
            Name.Add("CROATIA");
            Name.Add("CUBA");
            Name.Add("CURACAO");
            Name.Add("CYPRUS");
            Name.Add("CZECH REPUBLIC");
            Name.Add("DAHOMEY");
            Name.Add("DENMARK");
            Name.Add("DJIBOUTI");
            Name.Add("DOMINICA");
            Name.Add("DOMINICAN REPUBLIC");
            Name.Add("DUBAI");
            Name.Add("ECUADOR");
            Name.Add("EGYPT");
            Name.Add("EL SALVADOR");
            Name.Add("EQUATORIAL GUINEA");
            Name.Add("ESTONIA");
            Name.Add("ETHIOPIA");
            Name.Add("FAEROE ISLANDS");
            Name.Add("FALKLAND ISLANDS");
            Name.Add("FIJI");
            Name.Add("FINLAND");
            Name.Add("FRENCH GUIANA");
            Name.Add("FRENCH POLYNESIA");
            Name.Add("GABON");
            Name.Add("GAMBIA");
            Name.Add("GEORGIA");
            Name.Add("GHANA");
            Name.Add("GIBRALTAR");
            Name.Add("GREECE");
            Name.Add("GREENLAND");
            Name.Add("GUADELOUPE");
            Name.Add("GUAM");
            Name.Add("GUATEMALA");
            Name.Add("GUINEA");
            Name.Add("GUYANA");
            Name.Add("HAITI");
            Name.Add("HONDURAS");
            Name.Add("HONG KONG");
            Name.Add("HUNGARY");
            Name.Add("ICELAND");
            Name.Add("IFNI");
            Name.Add("INDIA");
            Name.Add("INDONESIA");
            Name.Add("IRAN");
            Name.Add("IRAQ");
            Name.Add("IRELAND");
            Name.Add("ISRAEL");
            Name.Add("IVORY COAST");
            Name.Add("JAMAICA");
            Name.Add("JAPAN");
            Name.Add("JORDAN");
            Name.Add("KAZAKHSTAN");
            Name.Add("KENYA");
            Name.Add("KOREA");
            Name.Add("KOREA");
            Name.Add("KUWAIT");
            Name.Add("KYRGYZSTAN");
            Name.Add("LAOS");
            Name.Add("LATVIA");
            Name.Add("LEBANON");
            Name.Add("LEEWARD ISLANDS");
            Name.Add("LESOTHO");
            Name.Add("LIBYA");
            Name.Add("LIECHTENSTEIN");
            Name.Add("LITHUANIA");
            Name.Add("LUXEMBOURG");
            Name.Add("MACAO");
            Name.Add("MACEDONIA");
            Name.Add("MADAGASCAR");
            Name.Add("MALAWI");
            Name.Add("MALAYSIA");
            Name.Add("MALDIVES");
            Name.Add("MALI");
            Name.Add("MALTA");
            Name.Add("MARTINIQUE");
            Name.Add("MAURITANIA");
            Name.Add("MAURITIUS");
            Name.Add("MELANESIA");
            Name.Add("MEXICO");
            Name.Add("MOLDOVIA");
            Name.Add("MONACO");
            Name.Add("MONGOLIA");
            Name.Add("MOROCCO");
            Name.Add("MOZAMBIQUE");
            Name.Add("MYANAMAR");
            Name.Add("NAMIBIA");
            Name.Add("NEPAL");
            Name.Add("NETHERLANDS");
            Name.Add("NETHERLANDS ANTILLES");
            Name.Add("NETHERLANDS ANTILLES NEUTRAL ZONE");
            Name.Add("NEW CALADONIA");
            Name.Add("NEW HEBRIDES");
            Name.Add("NEW ZEALAND");
            Name.Add("NICARAGUA");
            Name.Add("NIGER");
            Name.Add("NIGERIA");
            Name.Add("NORFOLK ISLAND");
            Name.Add("NORWAY");
            Name.Add("OMAN");
            Name.Add("OTHER");
            Name.Add("PACIFIC ISLAND");
            Name.Add("PAKISTAN");
            Name.Add("PANAMA");
            Name.Add("PAPUA NEW GUINEA");
            Name.Add("PARAGUAY");
            Name.Add("PERU");
            Name.Add("PHILIPPINES");
            Name.Add("POLAND");
            Name.Add("PORTUGAL");
            Name.Add("PORTUGUESE TIMOR");
            Name.Add("PUERTO RICO");
            Name.Add("QATAR");
            Name.Add("REPUBLIC OF BELARUS");
            Name.Add("REPUBLIC OF SOUTH AFRICA");
            Name.Add("REUNION");
            Name.Add("ROMANIA");
            Name.Add("RUSSIA");
            Name.Add("RWANDA");
            Name.Add("RYUKYU ISLANDS");
            Name.Add("SABAH");
            Name.Add("SAN MARINO");
            Name.Add("SAUDI ARABIA");
            Name.Add("SENEGAL");
            Name.Add("SERBIA");
            Name.Add("SEYCHELLES");
            Name.Add("SIERRA LEONE");
            Name.Add("SINGAPORE");
            Name.Add("SLOVAKIA");
            Name.Add("SLOVENIA");
            Name.Add("SOMALILIAND");
            Name.Add("SOUTH AFRICA");
            Name.Add("SOUTH YEMEN");
            Name.Add("SPANISH SAHARA");
            Name.Add("SRI LANKA");
            Name.Add("ST. KITTS AND NEVIS");
            Name.Add("ST. LUCIA");
            Name.Add("SUDAN");
            Name.Add("SURINAM");
            Name.Add("SW AFRICA");
            Name.Add("SWAZILAND");
            Name.Add("SWEDEN");
            Name.Add("SWITZERLAND");
            Name.Add("SYRIA");
            Name.Add("TAIWAN");
            Name.Add("TAJIKISTAN");
            Name.Add("TANZANIA");
            Name.Add("THAILAND");
            Name.Add("TONGA");
            Name.Add("TRINIDAD");
            Name.Add("TUNISIA");
            Name.Add("TURKEY");
            Name.Add("UGANDA");
            Name.Add("UKRAINE");
            Name.Add("UNITED ARAB EMIRATES");
            Name.Add("UPPER VOLTA");
            Name.Add("URUGUAY");
            Name.Add("US PACIFIC ISLAND");
            Name.Add("US VIRGIN ISLANDS");
            Name.Add("USA");
            Name.Add("UZBEKISTAN");
            Name.Add("VANUATU");
            Name.Add("VATICAN CITY");
            Name.Add("VENEZUELA");
            Name.Add("VIETNAM");
            Name.Add("WAKE ISLAND");
            Name.Add("WEST INDIES");
            Name.Add("WESTERN SAHARA");
            Name.Add("YEMEN");
            Name.Add("ZAIRE");
            Name.Add("ZAMBIA");
            Name.Add("ZIMBABWE");
        }
    }
}
